# Generated by Django 5.0.3 on 2024-03-31 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('picture', models.ImageField(upload_to='books')),
                ('writer_name', models.CharField(max_length=260)),
                ('regular_price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, default=models.IntegerField(), null=True)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Languege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languege_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(null=True, upload_to='course_image')),
                ('course_video', models.CharField(max_length=650, null=True)),
                ('title_1', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('skill_level', models.CharField(blank=True, max_length=160, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('certificate', models.CharField(blank=True, max_length=20, null=True)),
                ('publish_satatus', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='clac.category')),
                ('languege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.languege')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs', to='clac.course')),
            ],
        ),
        migrations.CreateModel(
            name='Requierment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_1', models.CharField(blank=True, max_length=260, null=True)),
                ('point_2', models.CharField(blank=True, max_length=260, null=True)),
                ('point_3', models.CharField(blank=True, max_length=260, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(null=True)),
                ('thumbnail', models.ImageField(upload_to='video_Thumbnail')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=200)),
                ('time_duration', models.IntegerField()),
                ('preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cls_video', to='clac.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_leson', to='clac.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Whats_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pont1', models.CharField(blank=True, max_length=190, null=True)),
                ('pont2', models.CharField(blank=True, default='', max_length=190, null=True)),
                ('pont3', models.CharField(blank=True, max_length=190, null=True)),
                ('pont4', models.CharField(blank=True, max_length=190, null=True)),
                ('pont5', models.CharField(blank=True, max_length=190, null=True)),
                ('pont6', models.CharField(blank=True, max_length=190, null=True)),
                ('pont7', models.CharField(blank=True, max_length=190, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clac.course')),
            ],
        ),
    ]
