# Generated by Django 4.1.4 on 2023-05-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0005_course_certificate_course_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
