# Generated by Django 4.1.4 on 2023-05-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0006_remove_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill_level',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
