# Generated by Django 4.1.4 on 2023-05-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0009_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
