# Generated by Django 4.1.4 on 2023-05-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0012_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
