# Generated by Django 4.1.4 on 2023-05-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clac', '0011_payment'),
        ('Student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs_review', to='clac.course'),
        ),
    ]
